name: nt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - comm=0.1.2
  - cryptography=39.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - importlib_metadata=6.0.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxgboost=1.7.3
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=3.0.9
  - packaging=23.0
  - pandas=1.4.2
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-xgboost=1.7.3
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.9.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xgboost=1.7.3
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - alembic==1.8.0
    - ansi2html==1.8.0
    - astunparse==1.6.3
    - cachetools==5.3.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cloudpickle==2.1.0
    - cmaes==0.9.1
    - colorlog==6.7.0
    - colour==0.1.5
    - dash==2.13.0
    - dash-auth==2.0.0
    - dash-bootstrap-components==1.5.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - databricks-cli==0.17.0
    - docker==5.0.3
    - dtreeviz==2.2.2
    - explainerdashboard==0.4.3
    - flask==2.1.2
    - flask-simplelogin==0.1.2
    - flask-wtf==1.1.1
    - flatbuffers==23.1.21
    - future==0.18.3
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==1.1.2
    - grpcio==1.51.3
    - gunicorn==20.1.0
    - h5py==3.8.0
    - hyperopt==0.2.7
    - idna==3.3
    - importlib-metadata==4.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jupyter-dash==0.4.2
    - keras==2.11.0
    - libclang==15.0.6.1
    - lightgbm==3.3.5
    - llvmlite==0.40.1rc1
    - mako==1.2.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mlflow==1.26.1
    - networkx==3.1
    - numba==0.57.0
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - optuna==3.2.0
    - oyaml==1.0
    - plotly==5.17.0
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.2
    - protobuf==3.19.6
    - py4j==0.10.9.7
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyjwt==2.4.0
    - python-graphviz==0.20.1
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - requests==2.28.0
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rsa==4.9
    - scikit-learn==1.3.1
    - scikit-optimize==0.9.0
    - shap==0.42.1
    - slicer==0.0.7
    - smmap==5.0.0
    - sqlalchemy==1.4.39
    - sqlparse==0.4.2
    - tabulate==0.8.10
    - tenacity==8.2.3
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-decision-forests==1.2.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - termcolor==2.2.0
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - urllib3==1.26.9
    - waitress==2.1.2
    - websocket-client==1.3.3
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - wtforms==3.0.1
    - wurlitzer==3.0.3
    - zipp==3.8.0
